language: node_js
node_js:
  - node

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

cache:
  directories:
    - client/node_modules
    - server/node_modules
    - $HOME/.local/bin

stages:
  - validate
  - name: deploy-staging
    if: type != pull_request AND branch = staging
  - name: deploy-production
    if: type != pull_request AND branch = master

jobs:
  include:
  - stage: validate
    name: Validate client
    install: ./platform/ci-client-install.sh
    script: ./platform/ci-client-validate.sh
  - name: Validate server
    install: ./platform/ci-server-install.sh
    script: ./platform/ci-server-validate.sh

  - stage: deploy-staging
    name: Deploy client
    env: STAGE=staging
    install:
      - ./platform/ci-client-install.sh
      - pip install --user awscli
    script: ./platform/ci-client-deploy.sh
  - name: Deploy server
    env: STAGE=staging
    install: ./platform/ci-server-install.sh
    script: ./platform/ci-server-deploy.sh

  - stage: deploy-production
    name: Deploy client
    env: STAGE=production
    install:
      - ./platform/ci-client-install.sh
      - pip install --user awscli
    script: ./platform/ci-client-deploy.sh
  - name: Deploy server
    env: STAGE=production
    install: ./platform/ci-server-install.sh
    script: ./platform/ci-server-deploy.sh
