language: node_js
node_js:
  - node

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

cache:
  directories:
    - client/node_modules
    - server/node_modules
    - $HOME/.local/bin

jobs:
  include:
  - stage: validate
    name: Validate client
    install: ./platform/ci-client-install.sh
    script: ./platform/ci-client-validate.sh
  - stage: validate
    name: Validate server
    install: ./platform/ci-server-install.sh
    script: ./platform/ci-server-validate.sh
  - stage: deploy
    name: Deploy client
    if: branch = master AND type != pull_request
    install:
      - ./platform/ci-client-install.sh
      - pip install --user awscli
    script: ./platform/ci-client-deploy.sh
  - stage: deploy
    name: Deploy server
    if: branch = master AND type != pull_request
    install: ./platform/ci-server-install.sh
    script: ./platform/ci-server-deploy.sh
