language: node_js
node_js:
  - node

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

cache:
  directories:
    - zhongwenguji-client/node_modules
    - zhongwenguji-server/node_modules
    - $HOME/.local/bin

script:
- echo "Install aws cli"
- pip install --user awscli
- echo "Build client"
- cd zhongwenguji-client
- npm install
- npm run build
- cd ..
- echo "Build Server"
- cd zhongwenguji-server
- npm install
- cd ..
- echo "Deploy client"
- cd zhongwenguji-client
- aws s3 sync build/ s3://$DEPLOY_S3_BUCKET
- cd ..
- echo "Deploy server"
- cd zhongwenguji-server
- ./node_modules/.bin/sls deploy
- cd ..
