language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- cd zhongwenguji-client
- npm install
- npm run build
- cd ../zhongwenguji-server
- npm install
- ./node_modules/.bin/sls deploy
