language: node_js
node_js:
  - node

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

cache:
  directories:
    - zhongwenguji-client/node_modules
    - zhongwenguji-server/node_modules
    - $HOME/.local/bin

install: ./platform/ci-install.sh

script:
- ./platform/ci-client-build.sh
- ./platform/ci-server-build.sh
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./platform/ci-client-deploy.sh; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./platform/ci-server-deploy.sh; fi'
