service: characters

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2
  stage: ${env:STAGE, 'development'}

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /getCharacterSample
          method: get
          cors: true
      - http:
          path: /submitTest
          method: post
          cors: true

plugins:
  - serverless-offline
